In [1]:
import pandas as pd

In [2]:
productos = pd.DataFrame({
    "id":[1,2,3],
    "nombre":["leche gloria" , "cocacola 9L" ,"SUBLIME"],
    "monto": [5.5, 6.5, 2.0]
    })
productos

   id        nombre  monto
0   1  leche gloria    5.5
1   2   cocacola 9L    6.5
2   3       SUBLIME    2.0

In [3]:
productos.sort_values("monto", ascending=False)

   id        nombre  monto
1   2   cocacola 9L    6.5
0   1  leche gloria    5.5
2   3       SUBLIME    2.0

In [6]:
productos["igv"] = productos ["monto"]*0.18
productos

   id        nombre  monto   igv
0   1  leche gloria    5.5  0.99
1   2   cocacola 9L    6.5  1.17
2   3       SUBLIME    2.0  0.36

In [7]:
productos["igv"] = productos["igv"].round(2)

In [8]:
print(productos)

   id        nombre  monto   igv
0   1  leche gloria    5.5  0.99
1   2   cocacola 9L    6.5  1.17
2   3       SUBLIME    2.0  0.36

In [9]:
prueba = 5.53 * 0.18
print(prueba)          # esto va a salir con muchos decimales
print(round(prueba, 2)) # esto lo redondea a 2

0.9954000000000001
1.0

In [10]:
productos[productos["nombre"].str.contains("cola", case=False)]

   id       nombre  monto   igv
1   2  cocacola 9L    6.5  1.17

In [11]:
productos.loc[productos["monto"].idxmax()]

id                  2
nombre    cocacola 9L
monto             6.5
igv              1.17
Name: 1, dtype: object

In [12]:
def clasificar(monto):
    if monto > 5:
        return "caro"
    else:
        return "barato"

productos["categoria"] = productos["monto"].apply(clasificar)
productos

   id        nombre  monto   igv categoria
0   1  leche gloria    5.5  0.99      caro
1   2   cocacola 9L    6.5  1.17      caro
2   3       SUBLIME    2.0  0.36    barato