In [1]:
import pandas as pd

In [2]:
boleta= pd.DataFrame({
    "idalumno":[1,2,3,4,5],
    "nombre":['SUSSIE','PEPE','ALBERTO','MATILDE','LEONY'],
    "u1":[12,15,14,16,11],
    "u2":[20,15,16,17,5],
    "u3":[13,13,14,13,5]
})
boleta

   idalumno   nombre  u1  u2  u3
0         1   SUSSIE  12  20  13
1         2     PEPE  15  15  13
2         3  ALBERTO  14  16  14
3         4  MATILDE  16  17  13
4         5    LEONY  11   5   5

In [4]:
boleta["promedio"] = (boleta["u1"] + boleta["u2"] + boleta["u3"]) / 3
boleta

   idalumno   nombre  u1  u2  u3   promedio
0         1   SUSSIE  12  20  13  15.000000
1         2     PEPE  15  15  13  14.333333
2         3  ALBERTO  14  16  14  14.666667
3         4  MATILDE  16  17  13  15.333333
4         5    LEONY  11   5   5   7.000000

In [5]:
boleta["promedio"] = boleta["promedio"].round(2)
boleta

   idalumno   nombre  u1  u2  u3  promedio
0         1   SUSSIE  12  20  13     15.00
1         2     PEPE  15  15  13     14.33
2         3  ALBERTO  14  16  14     14.67
3         4  MATILDE  16  17  13     15.33
4         5    LEONY  11   5   5      7.00

In [6]:
def estado_alumno(promedio):
    if promedio >= 10.5:
        return "APROBADO"
    else:
        return "DESAPROBADO"

boleta["estado"] = boleta["promedio"].apply(estado_alumno)
boleta

   idalumno   nombre  u1  u2  u3  promedio       estado
0         1   SUSSIE  12  20  13     15.00     APROBADO
1         2     PEPE  15  15  13     14.33     APROBADO
2         3  ALBERTO  14  16  14     14.67     APROBADO
3         4  MATILDE  16  17  13     15.33     APROBADO
4         5    LEONY  11   5   5      7.00  DESAPROBADO

In [7]:
boleta["estado"].value_counts()

estado
APROBADO       4
DESAPROBADO    1
Name: count, dtype: int64

In [8]:
boleta.loc[boleta["promedio"].idxmax()]  # el de mejor promedio
boleta.loc[boleta["promedio"].idxmin()]  # el de peor promedio

idalumno              5
nombre            LEONY
u1                   11
u2                    5
u3                    5
promedio            7.0
estado      DESAPROBADO
Name: 4, dtype: object

In [9]:
boleta.sort_values("promedio", ascending=False)

   idalumno   nombre  u1  u2  u3  promedio       estado
3         4  MATILDE  16  17  13     15.33     APROBADO
0         1   SUSSIE  12  20  13     15.00     APROBADO
2         3  ALBERTO  14  16  14     14.67     APROBADO
1         2     PEPE  15  15  13     14.33     APROBADO
4         5    LEONY  11   5   5      7.00  DESAPROBADO