Ejercicio 1 — Explorar el DataFrame

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\ant dor\appdata\local\programs\python\python313\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ant dor\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ant dor\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ant dor\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ant dor\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\ant dor\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: C:\Users\ANT DOR\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [1]:
import sys
print(sys.executable)
print(sys.version)

c:\Users\ANT DOR\AppData\Local\Programs\Python\Python313\python.exe
3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)]

In [10]:
import sys
print(sys.executable)

c:\Users\ANT DOR\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [3]:
escuelas = pd.DataFrame({
    "id": [1, 2, 3],
    "nombre": ["anthony", "juan", "maryori"],
    "descripcion": ["tecnologia", "ingles", "matematica"]
})

escuelas

   id   nombre descripcion
0   1  anthony  tecnologia
1   2     juan      ingles
2   3  maryori  matematica

In [4]:
escuelas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           3 non-null      int64
 1   nombre       3 non-null      object
 2   descripcion  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [5]:
escuelas.describe()

        id
count  3.0
mean   2.0
std    1.0
min    1.0
25%    1.5
50%    2.0
75%    2.5
max    3.0

In [6]:
escuelas["nombre"]

0    anthony
1       juan
2    maryori
Name: nombre, dtype: object

In [7]:
escuelas["cupos"] = [30, 25, 40]

In [9]:
escuelas["cupos_disponibles"] = escuelas["cupos"] - 5

In [10]:
print(escuelas)

   id   nombre descripcion  cupos  cupos_disponibles
0   1  anthony  tecnologia     30                 25
1   2     juan      ingles     25                 20
2   3  maryori  matematica     40                 35

In [12]:
escuelas.loc[25, "cupos"] = 99

In [13]:
print(escuelas)

     id   nombre descripcion  cupos  cupos_disponibles
0   1.0  anthony  tecnologia   30.0               25.0
1   2.0     juan      ingles   25.0               20.0
2   3.0  maryori  matematica   40.0               35.0
25  NaN      NaN         NaN   99.0                NaN

In [14]:
escuelas = escuelas.drop(25)

In [15]:
escuelas.loc[1, "cupos"] = 99

In [16]:
escuelas.loc[escuelas["cupos"] == 99, "cupos"] = 666

In [17]:
print(escuelas)

    id   nombre descripcion  cupos  cupos_disponibles
0  1.0  anthony  tecnologia   30.0               25.0
1  2.0     juan      ingles  666.0               20.0
2  3.0  maryori  matematica   40.0               35.0

In [18]:
pagos = pd.Series([120, 50, 30, 200, 500])

In [22]:
pagos[(pagos > 50) & (pagos < 300)]

0    120
3    200
dtype: int64